/**
 * Curated label icons. Each is a 64-dot-tall 1-bit PNG in
 * src/assets/label-icons/<id>.png (widths vary), made from a Tabler Icons
 * (MIT), Material Design Icons (Apache 2.0), IconMind (MIT) or Fluent UI
 * System Icons (MIT) icon, the Lesser Coat of Arms of Ukraine from Wikimedia
 * Commons (public domain), or taken from a Brother P-touch app screenshot
 * (`source: 'screenshot'`). RC icons also come from Lucide (ISC), Phosphor
 * (MIT), Fontisto (MIT), Line Awesome, MingCute and Carbon (Apache 2.0),
 * game-icons.net (CC BY 3.0, by Lorc, Delapouite and contributors), Streamline
 * (CC BY 4.0, streamlinehq.com), QGroundControl (`qgc:`, Apache 2.0; the elevon
 * is its flying wing with the elevons cut out) and SVG Repo (`svgrepo:`, CC0).
 * Smaller heights are shrunk from the 64-dot dots by `scaleIcon`.
 *
 * The PNGs are decoded once at start-up (see labelIconAssets.ts) and handed over
 * with `registerIconDots`. The dots, not the PNGs, are what prints and what
 * the app shows: the editor displays the same bitmap the printer receives.
 */
import { type IconBitmap, forEachRun, scaleIcon, scaledWidth } from './iconScale'
import { type UserIcon, unpackDots } from './userIcons'

export type { IconBitmap }

/** Height of the icon PNGs in dots. */
export const ICON_GRID = 64

export interface LabelIcon {
  id: string
  name: string
  /** Picker categories the icon is listed under (it is always in All). */
  categories: readonly IconCategory[]
  /** Width of the PNG in dots. */
  width: number
  /**
   * Where the dots come from: a set icon (`tabler:…`, `fluent:…`, …),
   * `screenshot`, or `user` for a pasted one.
   */
  source: string
}

/** Picker categories, in the order the picker shows them. */
export const ICON_CATEGORIES = [
  { id: 'signs', name: 'Signs' },
  { id: 'home', name: 'Home' },
  { id: 'nature', name: 'Nature' },
  { id: 'work', name: 'Work' },
  { id: 'engineering', name: 'Engineering' },
  { id: 'sport', name: 'Sport' },
  { id: 'food', name: 'Food' },
  /** Icons the user pasted in (see userIcons.ts); listed even when empty. */
  { id: 'user', name: 'User' },
] as const

export type IconCategory = (typeof ICON_CATEGORIES)[number]['id']

// prettier-ignore
export const LABEL_ICONS: readonly LabelIcon[] = [
  { id: 'paint-roller', name: 'Paint roller', categories: ['engineering'], width: 61, source: 'tabler:paint' },
  { id: 'paint-bucket', name: 'Paint bucket', categories: ['engineering'], width: 50, source: 'screenshot' },
  { id: 'brush', name: 'Brush', categories: ['engineering'], width: 46, source: 'fluent:paint-brush-24-regular' },
  { id: 'warning', name: 'Warning', categories: ['signs'], width: 64, source: 'tabler:alert-triangle' },
  { id: 'high-voltage', name: 'High voltage warning', categories: ['signs'], width: 64, source: 'screenshot' },
  { id: 'fire-extinguisher', name: 'Fire extinguisher', categories: ['signs'], width: 40, source: 'tabler:fire-extinguisher' },
  { id: 'recycle', name: 'Recycle', categories: ['signs'], width: 64, source: 'mdi:recycle-variant' },
  { id: 'hammer', name: 'Hammer', categories: ['engineering'], width: 64, source: 'screenshot' },
  { id: 'screwdriver', name: 'Screwdriver', categories: ['engineering'], width: 64, source: 'mdi:screwdriver' },
  { id: 'hand-saw', name: 'Saw', categories: ['engineering'], width: 64, source: 'mdi:hand-saw' },
  { id: 'wrench', name: 'Wrench', categories: ['engineering'], width: 64, source: 'screenshot' },
  { id: 'axe', name: 'Axe', categories: ['engineering'], width: 64, source: 'mdi:axe' },
  { id: 'nail', name: 'Nail', categories: ['engineering'], width: 28, source: 'screenshot' },
  { id: 'screw', name: 'Screw', categories: ['engineering'], width: 29, source: 'screenshot' },
  { id: 'nut', name: 'Nut', categories: ['engineering'], width: 64, source: 'screenshot' },
  { id: 'pliers', name: 'Pliers', categories: ['engineering'], width: 64, source: 'mdi:pliers' },
  { id: 'saw-blade', name: 'Saw blade', categories: ['engineering'], width: 64, source: 'mdi:saw-blade' },
  { id: 'toolbox', name: 'Toolbox', categories: ['engineering'], width: 64, source: 'mdi:toolbox-outline' },
  { id: 'ladder', name: 'Ladder', categories: ['engineering'], width: 34, source: 'tabler:ladder' },
  { id: 'watering-can', name: 'Watering can', categories: ['nature'], width: 64, source: 'mdi:watering-can-outline' },
  { id: 'rake', name: 'Rake', categories: ['engineering'], width: 64, source: 'mdi:rake' },
  { id: 'trowel', name: 'Trowel', categories: ['engineering'], width: 64, source: 'screenshot' },
  { id: 'shovel', name: 'Shovel', categories: ['engineering'], width: 61, source: 'tabler:shovel' },
  { id: 'lawn-mower', name: 'Lawn mower', categories: ['engineering'], width: 64, source: 'tabler:lawn-mower' },
  { id: 'wheelbarrow', name: 'Wheelbarrow', categories: ['engineering'], width: 64, source: 'tabler:garden-cart' },
  { id: 'fire', name: 'Fire', categories: ['nature'], width: 52, source: 'tabler:flame' },
  { id: 'bomb', name: 'Bomb', categories: ['signs'], width: 64, source: 'tabler:bomb' },
  { id: 'skull', name: 'Poison', categories: ['signs'], width: 61, source: 'screenshot' },
  { id: 'cordless-drill', name: 'Cordless drill', categories: ['engineering'], width: 64, source: 'screenshot' },
  { id: 'tape-roll', name: 'Tape roll', categories: ['engineering'], width: 57, source: 'screenshot' },
  { id: 'info', name: 'Info', categories: ['signs'], width: 64, source: 'screenshot' },
  { id: 'help', name: 'Question', categories: ['signs'], width: 64, source: 'screenshot' },
  { id: 'no-entry', name: 'No entry', categories: ['signs'], width: 64, source: 'tabler:circle-minus' },
  { id: 'prohibited', name: 'Prohibited', categories: ['signs'], width: 64, source: 'tabler:ban' },
  { id: 'no-smoking', name: 'No smoking', categories: ['signs'], width: 64, source: 'screenshot' },
  { id: 'no-parking', name: 'No parking', categories: ['signs'], width: 64, source: 'screenshot' },
  { id: 'no-touching', name: 'Do not touch', categories: ['signs'], width: 64, source: 'tabler:hand-off' },
  { id: 'no-phones', name: 'No phones', categories: ['signs'], width: 64, source: 'tabler:device-mobile-off' },
  { id: 'no-laptops', name: 'No laptops', categories: ['signs'], width: 64, source: 'tabler:device-laptop-off' },
  { id: 'no-photos', name: 'No photos', categories: ['signs'], width: 64, source: 'tabler:camera-off' },
  { id: 'no-food', name: 'No food', categories: ['signs'], width: 64, source: 'tabler:tools-kitchen-off' },
  { id: 'no-pets', name: 'No pets', categories: ['signs'], width: 64, source: 'tabler:paw-off' },
  { id: 'no-cards', name: 'No cards', categories: ['signs'], width: 64, source: 'tabler:credit-card-off' },
  { id: 'credit-card', name: 'Credit card', categories: ['work'], width: 64, source: 'tabler:credit-card' },
  { id: 'smoking', name: 'Smoking', categories: ['signs'], width: 64, source: 'tabler:smoking' },
  { id: 'exit', name: 'Exit', categories: ['signs'], width: 64, source: 'tabler:door-exit' },
  { id: 'man', name: 'Man', categories: ['signs'], width: 52, source: 'tabler:man' },
  { id: 'woman', name: 'Woman', categories: ['signs'], width: 52, source: 'tabler:woman' },
  { id: 'wheelchair', name: 'Wheelchair', categories: ['signs'], width: 56, source: 'screenshot' },
  { id: 'escalator', name: 'Escalator', categories: ['signs'], width: 64, source: 'tabler:escalator' },
  { id: 'stairs', name: 'Stairs', categories: ['signs'], width: 64, source: 'tabler:stairs-up' },
  { id: 'trash', name: 'Trash', categories: ['home'], width: 58, source: 'tabler:trash' },
  { id: 'elevator', name: 'Elevator', categories: ['signs'], width: 52, source: 'tabler:elevator' },
  { id: 'this-side-up', name: 'This side up', categories: ['signs'], width: 40, source: 'iconmind:arrow-up-from-line-outline-regular' },
  { id: 'fragile', name: 'Fragile', categories: ['signs'], width: 38, source: 'screenshot' },
  { id: 'keep-dry', name: 'Keep dry', categories: ['signs'], width: 64, source: 'fluent:umbrella-24-regular' },
  { id: 'antenna', name: 'Antenna', categories: ['engineering'], width: 64, source: 'screenshot' },
  { id: 'signal', name: 'Signal', categories: ['engineering'], width: 64, source: 'screenshot' },
  { id: 'ground', name: 'Ground', categories: ['engineering'], width: 64, source: 'screenshot' },
  { id: 'wifi', name: 'Wi-Fi', categories: ['engineering'], width: 64, source: 'iconmind:wifi-outline-regular' },
  { id: 'qr-code', name: 'QR code', categories: ['work'], width: 58, source: 'fluent:qr-code-24-regular' },
  { id: 'fuel', name: 'Fuel', categories: ['engineering'], width: 61, source: 'tabler:gas-station' },
  { id: 'first-aid', name: 'First aid', categories: ['signs'], width: 58, source: 'tabler:first-aid-kit' },
  { id: 'cctv', name: 'CCTV', categories: ['signs'], width: 64, source: 'screenshot' },
  { id: 'barrier', name: 'Barrier', categories: ['engineering'], width: 58, source: 'tabler:barrier-block' },
  { id: 'traffic-cone', name: 'Traffic cone', categories: ['engineering'], width: 48, source: 'screenshot' },
  { id: 'truck', name: 'Truck', categories: ['engineering'], width: 64, source: 'tabler:truck' },
  { id: 'faucet', name: 'Faucet', categories: ['home'], width: 64, source: 'screenshot' },
  { id: 'house', name: 'House', categories: ['home'], width: 64, source: 'tabler:home' },
  { id: 'building', name: 'Building', categories: ['work'], width: 64, source: 'tabler:building' },
  { id: 'no-fire', name: 'No open fire', categories: ['signs'], width: 64, source: 'tabler:flame-off' },
  { id: 'spade', name: 'Spade', categories: ['signs'], width: 58, source: 'tabler:spade' },
  { id: 'heart', name: 'Heart', categories: ['signs'], width: 64, source: 'tabler:heart' },
  { id: 'diamond', name: 'Diamond', categories: ['signs'], width: 46, source: 'mdi:cards-diamond-outline' },
  { id: 'club', name: 'Club', categories: ['signs'], width: 64, source: 'tabler:clubs' },
  { id: 'shopping-bag', name: 'Shopping bag', categories: ['home'], width: 58, source: 'tabler:shopping-bag' },
  { id: 'handle-with-care', name: 'Handle with care', categories: ['signs'], width: 55, source: 'screenshot' },
  { id: 'star', name: 'Star', categories: ['signs'], width: 64, source: 'tabler:star' },
  { id: 'star-filled', name: 'Star (filled)', categories: ['signs'], width: 64, source: 'tabler:star-filled' },
  { id: 'circle', name: 'Circle', categories: ['signs'], width: 64, source: 'tabler:circle' },
  { id: 'circle-filled', name: 'Circle (filled)', categories: ['signs'], width: 64, source: 'tabler:circle-filled' },
  { id: 'circle-double', name: 'Double circle', categories: ['signs'], width: 64, source: 'mdi:circle-double' },
  { id: 'square', name: 'Square', categories: ['signs'], width: 64, source: 'tabler:square' },
  { id: 'square-filled', name: 'Square (filled)', categories: ['signs'], width: 64, source: 'tabler:square-filled' },
  { id: 'diamond-filled', name: 'Rhombus (filled)', categories: ['signs'], width: 64, source: 'tabler:square-rotated-filled' },
  { id: 'triangle-up', name: 'Triangle up', categories: ['signs'], width: 64, source: 'tabler:triangle' },
  { id: 'triangle-down', name: 'Triangle down', categories: ['signs'], width: 64, source: 'tabler:triangle-inverted' },
  { id: 'triangle-up-filled', name: 'Triangle up (filled)', categories: ['signs'], width: 64, source: 'tabler:triangle-filled' },
  { id: 'triangle-down-filled', name: 'Triangle down (filled)', categories: ['signs'], width: 64, source: 'tabler:triangle-inverted-filled' },
  { id: 'triangle-left', name: 'Triangle left', categories: ['signs'], width: 28, source: 'tabler:caret-left' },
  { id: 'triangle-right', name: 'Triangle right', categories: ['signs'], width: 28, source: 'tabler:caret-right' },
  { id: 'triangle-left-filled', name: 'Triangle left (filled)', categories: ['signs'], width: 28, source: 'tabler:caret-left-filled' },
  { id: 'triangle-right-filled', name: 'Triangle right (filled)', categories: ['signs'], width: 28, source: 'tabler:caret-right-filled' },
  { id: 'arrow-left', name: 'Arrow left', categories: ['signs'], width: 52, source: 'tabler:arrow-left' },
  { id: 'arrow-up', name: 'Arrow up', categories: ['signs'], width: 46, source: 'tabler:arrow-up' },
  { id: 'arrow-right', name: 'Arrow right', categories: ['signs'], width: 52, source: 'tabler:arrow-right' },
  { id: 'arrow-down', name: 'Arrow down', categories: ['signs'], width: 46, source: 'tabler:arrow-down' },
  { id: 'arrow-up-left', name: 'Arrow up-left', categories: ['signs'], width: 40, source: 'tabler:arrow-up-left' },
  { id: 'arrow-up-right', name: 'Arrow up-right', categories: ['signs'], width: 40, source: 'tabler:arrow-up-right' },
  { id: 'arrow-down-right', name: 'Arrow down-right', categories: ['signs'], width: 40, source: 'tabler:arrow-down-right' },
  { id: 'arrow-down-left', name: 'Arrow down-left', categories: ['signs'], width: 40, source: 'tabler:arrow-down-left' },
  { id: 'bold-arrow-left', name: 'Bold arrow left', categories: ['signs'], width: 64, source: 'iconmind:arrow-big-left-outline-regular' },
  { id: 'bold-arrow-up', name: 'Bold arrow up', categories: ['signs'], width: 64, source: 'iconmind:arrow-big-up-outline-regular' },
  { id: 'bold-arrow-right', name: 'Bold arrow right', categories: ['signs'], width: 64, source: 'iconmind:arrow-big-right-outline-regular' },
  { id: 'bold-arrow-down', name: 'Bold arrow down', categories: ['signs'], width: 64, source: 'iconmind:arrow-big-down-outline-regular' },
  { id: 'bold-arrow-up-left', name: 'Bold arrow up-left', categories: ['signs'], width: 52, source: 'mdi:arrow-top-left-bold-outline' },
  { id: 'bold-arrow-up-right', name: 'Bold arrow up-right', categories: ['signs'], width: 52, source: 'mdi:arrow-top-right-bold-outline' },
  { id: 'bold-arrow-down-right', name: 'Bold arrow down-right', categories: ['signs'], width: 52, source: 'mdi:arrow-bottom-right-bold-outline' },
  { id: 'bold-arrow-down-left', name: 'Bold arrow down-left', categories: ['signs'], width: 52, source: 'mdi:arrow-bottom-left-bold-outline' },
  { id: 'fast-left', name: 'Fast arrow left', categories: ['signs'], width: 64, source: 'tabler:arrow-big-left-lines' },
  { id: 'fast-up', name: 'Fast arrow up', categories: ['signs'], width: 56, source: 'tabler:arrow-big-up-lines' },
  { id: 'fast-right', name: 'Fast arrow right', categories: ['signs'], width: 64, source: 'tabler:arrow-big-right-lines' },
  { id: 'fast-down', name: 'Fast arrow down', categories: ['signs'], width: 56, source: 'tabler:arrow-big-down-lines' },
  { id: 'hand-left', name: 'Hand pointing left', categories: ['signs'], width: 64, source: 'tabler:hand-finger-left' },
  { id: 'hand-up', name: 'Hand pointing up', categories: ['signs'], width: 59, source: 'tabler:hand-finger' },
  { id: 'hand-right', name: 'Hand pointing right', categories: ['signs'], width: 64, source: 'tabler:hand-finger-right' },
  { id: 'hand-down', name: 'Hand pointing down', categories: ['signs'], width: 59, source: 'tabler:hand-finger-down' },
  { id: 'swap', name: 'Swap', categories: ['signs'], width: 64, source: 'tabler:arrows-exchange' },
  { id: 'arrows-left-right', name: 'Left and right', categories: ['signs'], width: 64, source: 'tabler:arrows-horizontal' },
  { id: 'arrows-up-down', name: 'Up and down', categories: ['signs'], width: 34, source: 'tabler:arrows-vertical' },
  { id: 'shuffle', name: 'Shuffle', categories: ['signs'], width: 64, source: 'tabler:arrows-shuffle' },
  { id: 'repeat', name: 'Repeat', categories: ['signs'], width: 58, source: 'tabler:repeat' },
  { id: 'cutlery', name: 'Cutlery', categories: ['food'], width: 55, source: 'fluent:food-24-regular' },
  { id: 'kettle', name: 'Kettle', categories: ['food'], width: 58, source: 'mdi:kettle-outline' },
  { id: 'glass', name: 'Glass', categories: ['food'], width: 58, source: 'mdi:cup-outline' },
  { id: 'frying-pan', name: 'Frying pan', categories: ['food'], width: 64, source: 'iconmind:frying-pan-outline-regular' },
  { id: 'salt', name: 'Salt shaker', categories: ['food'], width: 48, source: 'tabler:salt' },
  { id: 'pot', name: 'Pot', categories: ['food'], width: 58, source: 'mdi:pot-outline' },
  { id: 'bowl', name: 'Bowl', categories: ['food'], width: 64, source: 'tabler:bowl' },
  { id: 'oven', name: 'Oven', categories: ['food'], width: 58, source: 'fluent:oven-24-regular' },
  { id: 'plate', name: 'Plate', categories: ['food'], width: 58, source: 'iconmind:plate-outline-regular' },
  { id: 'ladle', name: 'Ladle', categories: ['food'], width: 64, source: 'tabler:ladle' },
  { id: 'coffee-maker', name: 'Coffee maker', categories: ['food'], width: 52, source: 'mdi:coffee-maker-outline' },
  { id: 'toaster', name: 'Toaster', categories: ['food'], width: 64, source: 'iconmind:toaster-outline-regular' },
  { id: 'microwave', name: 'Microwave', categories: ['food'], width: 64, source: 'tabler:microwave' },
  { id: 'fridge', name: 'Fridge', categories: ['food'], width: 50, source: 'iconmind:fridge-outline-regular' },
  { id: 'spoons', name: 'Spoon', categories: ['food'], width: 59, source: 'mdi:silverware-spoon' },
  { id: 'whisk', name: 'Whisk', categories: ['food'], width: 64, source: 'tabler:whisk' },
  { id: 'teapot', name: 'Teapot', categories: ['food'], width: 64, source: 'tabler:teapot' },
  { id: 'bottle-opener', name: 'Bottle opener', categories: ['food'], width: 60, source: 'screenshot' },
  { id: 'lid', name: 'Lid', categories: ['food'], width: 64, source: 'screenshot' },
  { id: 'oven-mitt', name: 'Oven mitt', categories: ['food'], width: 63, source: 'screenshot' },
  { id: 'hand-mixer', name: 'Hand mixer', categories: ['food'], width: 61, source: 'screenshot' },
  { id: 'chopsticks', name: 'Bowl and chopsticks', categories: ['food'], width: 64, source: 'fluent:chopsticks-24-regular' },
  { id: 'chef-knife', name: 'Chef knife', categories: ['food'], width: 60, source: 'mdi:knife' },
  { id: 'spatula', name: 'Spatula', categories: ['food'], width: 64, source: 'tabler:grill-spatula' },
  { id: 'bottles', name: 'Bottle', categories: ['food'], width: 40, source: 'tabler:bottle' },
  { id: 'measuring-cup', name: 'Measuring cup', categories: ['food'], width: 55, source: 'iconmind:measuring-cup-outline-regular' },
  { id: 'coffee-cup', name: 'Coffee cup', categories: ['food'], width: 64, source: 'tabler:coffee' },
  { id: 'mug', name: 'Mug', categories: ['food'], width: 64, source: 'tabler:mug' },
  { id: 'shopping-cart', name: 'Shopping cart', categories: ['home'], width: 58, source: 'tabler:shopping-cart' },
  { id: 'chef-hat', name: 'Chef hat', categories: ['food'], width: 64, source: 'tabler:chef-hat' },
  { id: 'pineapple', name: 'Pineapple', categories: ['food'], width: 44, source: 'mdi:fruit-pineapple' },
  { id: 'apple', name: 'Apple', categories: ['food'], width: 58, source: 'tabler:apple' },
  { id: 'banana', name: 'Banana', categories: ['food'], width: 64, source: 'tabler:banana' },
  { id: 'grapes', name: 'Grapes', categories: ['food'], width: 46, source: 'tabler:grape' },
  { id: 'watermelon', name: 'Watermelon', categories: ['food'], width: 64, source: 'mdi:fruit-watermelon' },
  { id: 'acorn', name: 'Acorn', categories: ['nature'], width: 52, source: 'tabler:acorn' },
  { id: 'cherries', name: 'Cherries', categories: ['food'], width: 58, source: 'tabler:cherry' },
  { id: 'citrus', name: 'Citrus', categories: ['food'], width: 64, source: 'tabler:lemon' },
  { id: 'egg', name: 'Egg', categories: ['food'], width: 50, source: 'mdi:egg-outline' },
  { id: 'carrot', name: 'Carrot', categories: ['food'], width: 64, source: 'tabler:carrot' },
  { id: 'mushroom', name: 'Mushroom', categories: ['food'], width: 64, source: 'mdi:mushroom-outline' },
  { id: 'broccoli', name: 'Broccoli', categories: ['food'], width: 60, source: 'screenshot' },
  { id: 'pumpkin', name: 'Pumpkin', categories: ['food'], width: 64, source: 'mdi:pumpkin' },
  { id: 'cake', name: 'Cake', categories: ['food'], width: 64, source: 'tabler:cake' },
  { id: 'ice-cream', name: 'Ice cream', categories: ['food'], width: 34, source: 'tabler:ice-cream' },
  { id: 'fish', name: 'Fish', categories: ['nature'], width: 64, source: 'tabler:fish' },
  { id: 'pear', name: 'Pear', categories: ['food'], width: 44, source: 'screenshot' },
  { id: 'strawberry', name: 'Strawberry', categories: ['food'], width: 56, source: 'screenshot' },
  { id: 'potato', name: 'Potato', categories: ['food'], width: 64, source: 'screenshot' },
  { id: 'tomato', name: 'Tomato', categories: ['food'], width: 64, source: 'screenshot' },
  { id: 'garlic', name: 'Garlic', categories: ['food'], width: 64, source: 'screenshot' },
  { id: 'asparagus', name: 'Asparagus', categories: ['food'], width: 36, source: 'screenshot' },
  { id: 'leafy-greens', name: 'Leaf', categories: ['nature'], width: 59, source: 'tabler:leaf' },
  { id: 'herb', name: 'Sprig', categories: ['nature'], width: 46, source: 'iconmind:herb-outline-regular' },
  { id: 'candy', name: 'Candy', categories: ['food'], width: 64, source: 'tabler:candy' },
  { id: 'bowl-spoon', name: 'Bowl with spoon', categories: ['food'], width: 64, source: 'tabler:bowl-spoon' },
  { id: 'cheese', name: 'Cheese', categories: ['food'], width: 64, source: 'tabler:cheese' },
  { id: 'butter', name: 'Butter', categories: ['food'], width: 64, source: 'iconmind:butter-outline-regular' },
  { id: 'cupcake', name: 'Cupcake', categories: ['food'], width: 64, source: 'mdi:cupcake' },
  { id: 'beer', name: 'Beer', categories: ['food'], width: 58, source: 'fluent:drink-beer-24-regular' },
  { id: 'smoothie', name: 'Smoothie', categories: ['food'], width: 52, source: 'tabler:bubble-tea' },
  { id: 'wine-bottle', name: 'Wine bottle', categories: ['food'], width: 28, source: 'mdi:bottle-wine-outline' },
  { id: 'wine-glass', name: 'Wine glass', categories: ['food'], width: 46, source: 'iconmind:wine-glass-outline-regular' },
  { id: 'coffee-to-go', name: 'Coffee to go', categories: ['food'], width: 52, source: 'fluent:drink-to-go-24-regular' },
  { id: 'milk', name: 'Milk', categories: ['food'], width: 46, source: 'tabler:milk' },
  { id: 'wheat', name: 'Wheat', categories: ['food'], width: 50, source: 'tabler:wheat' },
  { id: 'water-bottle', name: 'Water bottle', categories: ['food'], width: 34, source: 'iconmind:reusable-bottle-outline-regular' },
  { id: 'olive-branch', name: 'Olive branch', categories: ['nature'], width: 64, source: 'screenshot' },
  { id: 'mouse', name: 'Mouse', categories: ['engineering'], width: 46, source: 'tabler:mouse' },
  { id: 'laptop', name: 'Laptop', categories: ['engineering'], width: 64, source: 'tabler:device-laptop' },
  { id: 'printer', name: 'Printer', categories: ['engineering'], width: 64, source: 'tabler:printer' },
  { id: 'scanner', name: 'Scanner', categories: ['engineering'], width: 58, source: 'mdi:scanner' },
  { id: 'fax', name: 'Fax', categories: ['engineering'], width: 64, source: 'mdi:fax' },
  { id: 'plug', name: 'Plug', categories: ['engineering'], width: 58, source: 'tabler:plug' },
  { id: 'socket', name: 'Socket', categories: ['engineering'], width: 64, source: 'mdi:power-socket-eu' },
  { id: 'telephone', name: 'Telephone', categories: ['engineering'], width: 61, source: 'tabler:phone' },
  { id: 'keyboard', name: 'Keyboard', categories: ['engineering'], width: 64, source: 'fluent:keyboard-24-regular' },
  { id: 'pushpin', name: 'Pushpin', categories: ['work'], width: 57, source: 'tabler:pin' },
  { id: 'paperclip', name: 'Paper clip', categories: ['work'], width: 64, source: 'tabler:paperclip' },
  { id: 'calendar', name: 'Calendar', categories: ['work'], width: 58, source: 'tabler:calendar-event' },
  { id: 'clipboard', name: 'Clipboard', categories: ['work'], width: 52, source: 'tabler:clipboard-text' },
  { id: 'paper-stack', name: 'Paper stack', categories: ['work'], width: 58, source: 'tabler:stack-2' },
  { id: 'folders', name: 'Folders', categories: ['work'], width: 64, source: 'tabler:folders' },
  { id: 'book', name: 'Book', categories: ['work'], width: 64, source: 'tabler:book' },
  { id: 'pen', name: 'Pen', categories: ['work'], width: 64, source: 'tabler:ballpen' },
  { id: 'mailbox', name: 'Mailbox', categories: ['work'], width: 64, source: 'tabler:mailbox' },
  { id: 'filing-cabinet', name: 'Filing cabinet', categories: ['work'], width: 52, source: 'mdi:file-cabinet' },
  { id: 'inbox', name: 'Inbox tray', categories: ['work'], width: 58, source: 'tabler:inbox' },
  { id: 'clock', name: 'Clock', categories: ['work'], width: 64, source: 'tabler:clock' },
  { id: 'mail', name: 'Mail', categories: ['work'], width: 64, source: 'tabler:mail' },
  { id: 'checkbox', name: 'Checkbox', categories: ['work'], width: 58, source: 'tabler:checkbox' },
  { id: 'check', name: 'Check', categories: ['signs'], width: 56, source: 'fluent:checkmark-24-regular' },
  { id: 'unlock', name: 'Unlocked', categories: ['home'], width: 52, source: 'iconmind:unlock-outline-regular' },
  { id: 'lock', name: 'Locked', categories: ['home'], width: 52, source: 'iconmind:lock-outline-regular' },
  { id: 'key', name: 'Key', categories: ['home'], width: 64, source: 'fluent:key-24-regular' },
  { id: 'pie-chart', name: 'Pie chart', categories: ['work'], width: 64, source: 'tabler:chart-pie' },
  { id: 'stapler', name: 'Stapler', categories: ['work'], width: 64, source: 'screenshot' },
  { id: 'binder-clip', name: 'Binder clip', categories: ['work'], width: 62, source: 'screenshot' },
  { id: 'bar-chart', name: 'Bar chart', categories: ['work'], width: 64, source: 'tabler:chart-bar' },
  { id: 'monitor', name: 'Monitor', categories: ['engineering'], width: 64, source: 'mdi:monitor' },
  { id: 'mobile-phone', name: 'Mobile phone', categories: ['engineering'], width: 31, source: 'mdi:cellphone-basic' },
  { id: 'sticky-note', name: 'Sticky note', categories: ['work'], width: 52, source: 'tabler:notes' },
  { id: 'usb-cable', name: 'USB', categories: ['engineering'], width: 46, source: 'tabler:usb' },
  { id: 'battery-charging', name: 'Battery charging', categories: ['engineering'], width: 58, source: 'tabler:battery-charging' },
  { id: 'tape-measure', name: 'Tape measure', categories: ['engineering'], width: 64, source: 'mdi:tape-measure' },
  { id: 'postage-stamp', name: 'Postage stamp', categories: ['work'], width: 64, source: 'mdi:postage-stamp' },
  { id: 'document', name: 'Document', categories: ['work'], width: 52, source: 'tabler:file' },
  { id: 'rubber-stamp', name: 'Rubber stamp', categories: ['work'], width: 64, source: 'tabler:rubber-stamp' },
  { id: 'desk', name: 'Desk', categories: ['work'], width: 64, source: 'fluent:desk-24-regular' },
  { id: 'office-chair', name: 'Office chair', categories: ['work'], width: 58, source: 'iconmind:office-chair-outline-regular' },
  { id: 'desk-lamp', name: 'Desk lamp', categories: ['work'], width: 52, source: 'tabler:lamp' },
  { id: 'bookshelf', name: 'Bookshelf', categories: ['home'], width: 58, source: 'mdi:bookshelf' },
  { id: 'hourglass', name: 'Hourglass', categories: ['work'], width: 40, source: 'mdi:hourglass' },
  { id: 'pencil', name: 'Pencil', categories: ['work'], width: 56, source: 'tabler:pencil' },
  { id: 'writing', name: 'Signature', categories: ['work'], width: 64, source: 'fluent:signature-24-regular' },
  { id: 'eraser', name: 'Eraser', categories: ['work'], width: 64, source: 'tabler:eraser' },
  { id: 'drawing-compass', name: 'Drawing compass', categories: ['engineering'], width: 52, source: 'mdi:math-compass' },
  { id: 'scissors', name: 'Scissors', categories: ['engineering'], width: 64, source: 'mdi:content-cut' },
  { id: 'protractor', name: 'Protractor', categories: ['engineering'], width: 64, source: 'iconmind:protractor-outline-regular' },
  { id: 'ruler', name: 'Ruler', categories: ['engineering'], width: 64, source: 'tabler:ruler-2' },
  { id: 'palette', name: 'Palette', categories: ['work'], width: 64, source: 'tabler:palette' },
  { id: 'school-bag', name: 'Backpack', categories: ['work'], width: 53, source: 'fluent:backpack-24-regular' },
  { id: 'diploma', name: 'Diploma', categories: ['work'], width: 64, source: 'tabler:certificate' },
  { id: 'box-cutter', name: 'Box cutter', categories: ['engineering'], width: 53, source: 'mdi:box-cutter' },
  { id: 'set-square', name: 'Set square', categories: ['engineering'], width: 52, source: 'mdi:set-square' },
  { id: 'globe', name: 'Globe', categories: ['work'], width: 64, source: 'fluent:globe-24-regular' },
  { id: 'graduation-cap', name: 'Graduation cap', categories: ['work'], width: 64, source: 'tabler:school' },
  { id: 'flask', name: 'Flask', categories: ['work'], width: 48, source: 'tabler:flask' },
  { id: 'flower', name: 'Flower', categories: ['nature'], width: 64, source: 'tabler:flower' },
  { id: 'sunflower', name: 'Sunflower', categories: ['nature'], width: 51, source: 'iconmind:sunflower-outline-regular' },
  { id: 'daisy', name: 'Poppy', categories: ['nature'], width: 64, source: 'mdi:flower-poppy' },
  { id: 'cherry-blossom', name: 'Cherry blossom', categories: ['nature'], width: 58, source: 'iconmind:blossom-outline-regular' },
  { id: 'clover', name: 'Clover', categories: ['nature'], width: 64, source: 'tabler:clover' },
  { id: 'tree', name: 'Tree', categories: ['nature'], width: 46, source: 'tabler:tree' },
  { id: 'rose', name: 'Rose', categories: ['nature'], width: 64, source: 'screenshot' },
  { id: 'tulip', name: 'Tulip', categories: ['nature'], width: 58, source: 'mdi:flower-tulip-outline' },
  { id: 'flower-box', name: 'Flower bed', categories: ['nature'], width: 58, source: 'iconmind:flower-bed-outline-regular' },
  { id: 'branch', name: 'Branch', categories: ['nature'], width: 64, source: 'tabler:twig' },
  { id: 'sprout', name: 'Sprout', categories: ['nature'], width: 64, source: 'tabler:seedling' },
  { id: 'cactus', name: 'Cactus', categories: ['nature'], width: 46, source: 'tabler:cactus' },
  { id: 'potted-plant', name: 'Potted plant', categories: ['nature'], width: 64, source: 'tabler:plant' },
  { id: 'maple-leaf', name: 'Maple leaf', categories: ['nature'], width: 58, source: 'tabler:leaf-maple' },
  { id: 'firework', name: 'Firework', categories: ['signs'], width: 64, source: 'screenshot' },
  { id: 'planet', name: 'Planet', categories: ['nature'], width: 64, source: 'tabler:planet' },
  { id: 'shooting-star', name: 'Shooting star', categories: ['nature'], width: 58, source: 'tabler:comet' },
  { id: 'candelabra', name: 'Candelabra', categories: ['home'], width: 56, source: 'mdi:candelabra' },
  { id: 'crown', name: 'Crown', categories: ['signs'], width: 64, source: 'fluent:crown-24-regular' },
  { id: 'hand-mirror', name: 'Mirror', categories: ['home'], width: 52, source: 'mdi:mirror' },
  { id: 'weathervane', name: 'Weathervane', categories: ['nature'], width: 46, source: 'iconmind:wind-vane-outline-regular' },
  { id: 'perfume', name: 'Perfume', categories: ['home'], width: 52, source: 'tabler:perfume' },
  { id: 'fleur-de-lis', name: 'Fleur-de-lis', categories: ['signs'], width: 58, source: 'mdi:fleur-de-lis' },
  { id: 'ukraine-trident', name: 'Ukraine trident', categories: ['signs'], width: 40, source: 'wikimedia:lesser-coat-of-arms-of-ukraine' },
  { id: 'ukraine-trident-shield', name: 'Ukraine trident in shield', categories: ['signs'], width: 48, source: 'wikimedia:lesser-coat-of-arms-of-ukraine' },
  { id: 'ukraine-coat-of-arms', name: 'Ukraine coat of arms', categories: ['signs'], width: 47, source: 'wikimedia:lesser-coat-of-arms-of-ukraine' },
  { id: 'sun', name: 'Sun', categories: ['nature'], width: 64, source: 'tabler:sun' },
  { id: 'moon-stars', name: 'Moon and stars', categories: ['nature'], width: 64, source: 'tabler:moon-stars' },
  { id: 'cloud', name: 'Cloud', categories: ['nature'], width: 64, source: 'tabler:cloud' },
  { id: 'rainbow', name: 'Rainbow', categories: ['nature'], width: 64, source: 'tabler:rainbow' },
  { id: 'anchor', name: 'Anchor', categories: ['engineering'], width: 64, source: 'tabler:anchor' },
  { id: 'ship-wheel', name: 'Ship wheel', categories: ['engineering'], width: 64, source: 'mdi:ship-wheel' },
  { id: 'lifebuoy', name: 'Lifebuoy', categories: ['signs'], width: 64, source: 'mdi:lifebuoy' },
  { id: 'laurel-wreath', name: 'Laurel wreath', categories: ['signs'], width: 64, source: 'tabler:laurel-wreath' },
  { id: 'light-bulb', name: 'Light bulb', categories: ['engineering'], width: 64, source: 'tabler:bulb' },
  { id: 'sparkles', name: 'Sparkles', categories: ['signs'], width: 61, source: 'tabler:sparkles' },
  { id: 'balloon', name: 'Balloon', categories: ['signs'], width: 47, source: 'tabler:balloon' },
  { id: 'magic-wand', name: 'Magic wand', categories: ['signs'], width: 64, source: 'tabler:wand' },
  { id: 'heart-with-arrow', name: 'Heart with arrow', categories: ['signs'], width: 64, source: 'screenshot' },
  { id: 'feather', name: 'Feather', categories: ['nature'], width: 58, source: 'tabler:feather' },
  { id: 'snowflake', name: 'Snowflake', categories: ['nature'], width: 60, source: 'tabler:snowflake' },
  { id: 'rocking-horse', name: 'Rocking horse', categories: ['home'], width: 64, source: 'tabler:horse-toy' },
  { id: 'sewing-machine', name: 'Sewing machine', categories: ['home'], width: 64, source: 'iconmind:sewing-machine-outline-regular' },
  { id: 'yarn', name: 'Yarn', categories: ['home'], width: 64, source: 'tabler:yarn' },
  { id: 'needle-thread', name: 'Needle and thread', categories: ['home'], width: 64, source: 'tabler:needle-thread' },
  { id: 'button', name: 'Button', categories: ['home'], width: 64, source: 'screenshot' },
  { id: 'safety-pin', name: 'Safety pin', categories: ['home'], width: 64, source: 'screenshot' },
  { id: 'party-popper', name: 'Party popper', categories: ['signs'], width: 64, source: 'mdi:party-popper' },
  { id: 'award', name: 'Award', categories: ['sport'], width: 64, source: 'tabler:award' },
  { id: 'cheers', name: 'Cheers', categories: ['food'], width: 64, source: 'iconmind:toast-glasses-outline-regular' },
  { id: 'party-hat', name: 'Party hat', categories: ['signs'], width: 52, source: 'iconmind:party-hat-outline-regular' },
  { id: 'diamond-ring', name: 'Ring', categories: ['signs'], width: 52, source: 'mdi:ring' },
  { id: 'gem', name: 'Gem', categories: ['signs'], width: 64, source: 'tabler:diamond' },
  { id: 'necklace', name: 'Necklace', categories: ['signs'], width: 64, source: 'mdi:necklace' },
  { id: 'gift', name: 'Gift', categories: ['signs'], width: 64, source: 'tabler:gift' },
  { id: 'confetti', name: 'Confetti', categories: ['signs'], width: 64, source: 'tabler:confetti' },
  { id: 'fishing', name: 'Fishing', categories: ['sport'], width: 55, source: 'iconmind:fishing-outline-regular' },
  { id: 'storm', name: 'Storm', categories: ['nature'], width: 64, source: 'tabler:cloud-storm' },
  { id: 'cleaning', name: 'Broom', categories: ['home'], width: 60, source: 'mdi:broom' },
  { id: 'trophy', name: 'Trophy', categories: ['sport'], width: 64, source: 'tabler:trophy' },
  { id: 'baby-stroller', name: 'Baby stroller', categories: ['home'], width: 64, source: 'tabler:baby-carriage' },
  { id: 'pacifier', name: 'Baby bottle', categories: ['home'], width: 64, source: 'mdi:baby-bottle-outline' },
  { id: 'dove', name: 'Bird', categories: ['nature'], width: 64, source: 'mdi:bird' },
  { id: 'yin-yang', name: 'Yin and yang', categories: ['signs'], width: 64, source: 'screenshot' },
  { id: 'rabbit', name: 'Rabbit', categories: ['nature'], width: 46, source: 'mdi:rabbit-variant-outline' },
  { id: 'turkey', name: 'Turkey', categories: ['nature'], width: 64, source: 'mdi:turkey' },
  { id: 'easter-egg', name: 'Easter egg', categories: ['signs'], width: 50, source: 'mdi:egg-easter' },
  { id: 'tent', name: 'Tent', categories: ['sport'], width: 64, source: 'tabler:tent' },
  { id: 'ghost', name: 'Ghost', categories: ['signs'], width: 54, source: 'tabler:ghost' },
  { id: 'jack-o-lantern', name: 'Jack-o-lantern', categories: ['signs'], width: 60, source: 'tabler:pumpkin-scary' },
  { id: 'bat', name: 'Bat', categories: ['nature'], width: 64, source: 'tabler:bat' },
  { id: 'bells', name: 'Bell', categories: ['signs'], width: 58, source: 'tabler:bell' },
  { id: 'bug-net', name: 'Butterfly net', categories: ['nature'], width: 64, source: 'screenshot' },
  { id: 'witch-hat', name: 'Witch hat', categories: ['signs'], width: 64, source: 'screenshot' },
  { id: 'candy-cane', name: 'Candy cane', categories: ['food'], width: 40, source: 'mdi:candycane' },
  { id: 'reindeer', name: 'Reindeer', categories: ['nature'], width: 64, source: 'tabler:deer' },
  { id: 'snowman', name: 'Snowman', categories: ['signs'], width: 58, source: 'tabler:snowman' },
  { id: 'christmas-tree', name: 'Christmas tree', categories: ['signs'], width: 52, source: 'tabler:christmas-tree' },
  { id: 'stocking', name: 'Stocking', categories: ['signs'], width: 52, source: 'tabler:sock' },
  { id: 'star-of-david', name: 'Star of David', categories: ['signs'], width: 58, source: 'mdi:star-david' },
  { id: 'sleigh', name: 'Sleigh', categories: ['signs'], width: 64, source: 'tabler:sleigh' },
  { id: 'gingerbread', name: 'Gingerbread man', categories: ['food'], width: 52, source: 'tabler:cookie-man' },
  { id: 'ornament', name: 'Ornament', categories: ['signs'], width: 58, source: 'tabler:christmas-ball' },
  { id: 'airplane', name: 'Airplane', categories: ['engineering'], width: 64, source: 'tabler:plane' },
  { id: 'train', name: 'Train', categories: ['engineering'], width: 52, source: 'mdi:locomotive' },
  { id: 'car', name: 'Car', categories: ['engineering'], width: 64, source: 'fluent:vehicle-car-profile-24-regular' },
  { id: 'scooter', name: 'Scooter', categories: ['engineering'], width: 58, source: 'tabler:scooter' },
  { id: 'koala', name: 'Koala', categories: ['nature'], width: 64, source: 'mdi:koala' },
  { id: 'rodent', name: 'Mouse (animal)', categories: ['nature'], width: 64, source: 'mdi:rodent' },
  { id: 'cow', name: 'Cow', categories: ['nature'], width: 64, source: 'mdi:cow' },
  { id: 'cat', name: 'Cat', categories: ['nature'], width: 64, source: 'tabler:cat' },
  { id: 'panda', name: 'Panda', categories: ['nature'], width: 64, source: 'mdi:panda' },
  { id: 'dinosaur', name: 'Dinosaur', categories: ['nature'], width: 64, source: 'mdi:dinosaur-pixel' },
  { id: 'duck', name: 'Duck', categories: ['nature'], width: 64, source: 'mdi:duck' },
  { id: 'butterfly', name: 'Butterfly', categories: ['nature'], width: 58, source: 'tabler:butterfly' },
  { id: 'teddy-bear', name: 'Teddy bear', categories: ['home'], width: 58, source: 'mdi:teddy-bear' },
  { id: 'baby', name: 'Baby', categories: ['home'], width: 64, source: 'mdi:baby-face-outline' },
  { id: 'robot', name: 'Robot', categories: ['engineering'], width: 52, source: 'tabler:robot' },
  { id: 'footprints', name: 'Footprints', categories: ['signs'], width: 54, source: 'mdi:footprints' },
  { id: 'unicorn', name: 'Unicorn', categories: ['nature'], width: 64, source: 'mdi:unicorn' },
  { id: 'horseshoe', name: 'Horseshoe', categories: ['signs'], width: 64, source: 'tabler:horseshoe' },
  { id: 'snake', name: 'Snake', categories: ['nature'], width: 64, source: 'mdi:snake' },
  { id: 'horse', name: 'Horse', categories: ['nature'], width: 64, source: 'tabler:horse' },
  { id: 'sheep', name: 'Sheep', categories: ['nature'], width: 64, source: 'mdi:emoji-sheep' },
  { id: 'pig', name: 'Pig', categories: ['nature'], width: 64, source: 'tabler:pig' },
  { id: 'dog', name: 'Dog', categories: ['nature'], width: 64, source: 'tabler:dog' },
  { id: 'dragon', name: 'Dragon', categories: ['nature'], width: 64, source: 'tabler:dragon' },
  { id: 'kangaroo', name: 'Kangaroo', categories: ['nature'], width: 64, source: 'mdi:kangaroo' },
  { id: 'owl', name: 'Owl', categories: ['nature'], width: 64, source: 'mdi:owl' },
  { id: 'penguin', name: 'Penguin', categories: ['nature'], width: 58, source: 'mdi:penguin' },
  { id: 'dolphin', name: 'Dolphin', categories: ['nature'], width: 64, source: 'mdi:dolphin' },
  { id: 'turtle', name: 'Turtle', categories: ['nature'], width: 64, source: 'mdi:turtle' },
  { id: 'beetle', name: 'Beetle', categories: ['nature'], width: 64, source: 'tabler:bug' },
  { id: 'ladybug', name: 'Ladybug', categories: ['nature'], width: 52, source: 'mdi:ladybug' },
  { id: 'bee', name: 'Bee', categories: ['nature'], width: 46, source: 'mdi:bee' },
  { id: 'snail', name: 'Snail', categories: ['nature'], width: 64, source: 'mdi:snail' },
  { id: 'paw', name: 'Paw print', categories: ['nature'], width: 64, source: 'tabler:paw' },
  { id: 'tennis-ball', name: 'Tennis ball', categories: ['sport'], width: 64, source: 'tabler:ball-tennis' },
  { id: 'soccer-ball', name: 'Soccer ball', categories: ['sport'], width: 64, source: 'tabler:ball-football' },
  { id: 'volleyball', name: 'Volleyball', categories: ['sport'], width: 64, source: 'tabler:ball-volleyball' },
  { id: 'basketball', name: 'Basketball', categories: ['sport'], width: 64, source: 'tabler:ball-basketball' },
  { id: 'american-football', name: 'American football', categories: ['sport'], width: 64, source: 'tabler:ball-american-football' },
  { id: 'football-helmet', name: 'Helmet', categories: ['sport'], width: 64, source: 'tabler:helmet' },
  { id: 'golf-ball', name: 'Golf ball', categories: ['sport'], width: 58, source: 'iconmind:golf-ball-outline-regular' },
  { id: 'tennis-racket', name: 'Tennis racket', categories: ['sport'], width: 64, source: 'mdi:tennis' },
  { id: 'badminton', name: 'Badminton', categories: ['sport'], width: 64, source: 'mdi:badminton' },
  { id: 'ping-pong', name: 'Ping pong', categories: ['sport'], width: 64, source: 'tabler:ping-pong' },
  { id: 'golf', name: 'Golf', categories: ['sport'], width: 43, source: 'tabler:golf' },
  { id: 'baseball', name: 'Baseball', categories: ['sport'], width: 64, source: 'tabler:ball-baseball' },
  { id: 'baseball-bat', name: 'Baseball bat', categories: ['sport'], width: 64, source: 'mdi:baseball-bat' },
  { id: 'bowling', name: 'Bowling', categories: ['sport'], width: 64, source: 'tabler:bowling' },
  { id: 'hockey', name: 'Hockey', categories: ['sport'], width: 64, source: 'mdi:hockey-sticks' },
  { id: 'skis', name: 'Skiing', categories: ['sport'], width: 64, source: 'mdi:ski' },
  { id: 'snowboard', name: 'Snowboard', categories: ['sport'], width: 64, source: 'tabler:snowboarding' },
  { id: 'surfing', name: 'Surfing', categories: ['sport'], width: 64, source: 'mdi:surfing' },
  { id: 'swimming', name: 'Swimming', categories: ['sport'], width: 64, source: 'tabler:swimming' },
  { id: 'diving', name: 'Diving', categories: ['sport'], width: 64, source: 'tabler:scuba-mask' },
  { id: 'beach', name: 'Beach', categories: ['sport'], width: 64, source: 'tabler:beach' },
  { id: 'ice-skate', name: 'Ice skate', categories: ['sport'], width: 64, source: 'tabler:ice-skating' },
  { id: 'skiing', name: 'Cross-country skiing', categories: ['sport'], width: 46, source: 'mdi:ski-cross-country' },
  { id: 'martial-arts', name: 'Martial arts', categories: ['sport'], width: 61, source: 'tabler:karate' },
  { id: 'skateboard', name: 'Skateboard', categories: ['sport'], width: 64, source: 'tabler:skateboard' },
  { id: 'hot-air-balloon', name: 'Hot air balloon', categories: ['engineering'], width: 56, source: 'tabler:air-balloon' },
  { id: 'roller-skate', name: 'Roller skate', categories: ['sport'], width: 58, source: 'tabler:roller-skating' },
  { id: 'gymnastics', name: 'Gymnastics', categories: ['sport'], width: 64, source: 'tabler:gymnastics' },
  { id: 'running', name: 'Running', categories: ['sport'], width: 52, source: 'tabler:run' },
  { id: 'wrestling', name: 'Wrestling', categories: ['sport'], width: 64, source: 'mdi:wrestling' },
  { id: 'beach-ball', name: 'Beach ball', categories: ['sport'], width: 64, source: 'screenshot' },
  { id: 'race-car', name: 'Race car', categories: ['engineering'], width: 64, source: 'mdi:car-sports' },
  { id: 'boxing', name: 'Boxing', categories: ['sport'], width: 64, source: 'mdi:boxing-glove' },
  { id: 'yoga', name: 'Yoga', categories: ['sport'], width: 58, source: 'tabler:yoga' },
  { id: 'exercise-bike', name: 'Cycling', categories: ['sport'], width: 64, source: 'mdi:bike' },
  { id: 'dumbbell', name: 'Dumbbell', categories: ['sport'], width: 64, source: 'tabler:barbell' },
  { id: 'running-shoe', name: 'Running shoe', categories: ['sport'], width: 64, source: 'mdi:shoe-sneaker' },
  { id: 'billiards', name: 'Billiards', categories: ['sport'], width: 64, source: 'mdi:billiards' },
  { id: 'playing-cards', name: 'Playing cards', categories: ['sport'], width: 64, source: 'tabler:cards' },
  { id: 'chess', name: 'Chess', categories: ['sport'], width: 64, source: 'fluent:chess-24-regular' },
  { id: 'dice', name: 'Dice', categories: ['sport'], width: 64, source: 'iconmind:dice-outline-regular' },
  { id: 'slot-machine', name: 'Slot machine', categories: ['sport'], width: 64, source: 'mdi:slot-machine-outline' },
  { id: 'roulette', name: 'Roulette', categories: ['sport'], width: 64, source: 'tabler:roulette' },
  { id: 'handheld-game', name: 'Handheld game', categories: ['sport'], width: 44, source: 'mdi:nintendo-game-boy' },
  { id: 'game-controller', name: 'Game controller', categories: ['sport'], width: 64, source: 'tabler:device-gamepad' },
  { id: 'paper-towel', name: 'Toilet paper', categories: ['home'], width: 64, source: 'tabler:toilet-paper' },
  { id: 'razor', name: 'Razor', categories: ['home'], width: 64, source: 'mdi:razor-double-edge' },
  { id: 'lipstick', name: 'Lipstick', categories: ['home'], width: 28, source: 'mdi:lipstick' },
  { id: 'pill', name: 'Pill', categories: ['home'], width: 64, source: 'fluent:pill-24-regular' },
  { id: 'medicine', name: 'Medicine', categories: ['home'], width: 46, source: 'iconmind:pill-bottle-outline-regular' },
  { id: 'syringe', name: 'Syringe', categories: ['home'], width: 64, source: 'tabler:vaccine' },
  { id: 'spray-bottle', name: 'Spray bottle', categories: ['home'], width: 64, source: 'tabler:spray' },
  { id: 'soap-dispenser', name: 'Soap dispenser', categories: ['home'], width: 58, source: 'mdi:lotion-outline' },
  { id: 'soap', name: 'Dish soap', categories: ['home'], width: 52, source: 'iconmind:dish-soap-outline-regular' },
  { id: 'hand-wash', name: 'Hand wash', categories: ['home'], width: 64, source: 'mdi:hand-wash-outline' },
  { id: 'battery', name: 'Battery', categories: ['engineering'], width: 58, source: 'tabler:battery-4' },
  { id: 'bandage', name: 'Bandage', categories: ['home'], width: 64, source: 'mdi:bandage' },
  { id: 'face-mask', name: 'Face mask', categories: ['home'], width: 64, source: 'tabler:face-mask' },
  { id: 'toothpaste', name: 'Toothpaste', categories: ['home'], width: 51, source: 'screenshot' },
  { id: 'towel', name: 'Towel', categories: ['home'], width: 64, source: 'screenshot' },
  { id: 'comb', name: 'Comb', categories: ['home'], width: 54, source: 'screenshot' },
  { id: 'hairbrush', name: 'Hairbrush', categories: ['home'], width: 60, source: 'screenshot' },
  { id: 'makeup-brush', name: 'Makeup brush', categories: ['home'], width: 64, source: 'screenshot' },
  { id: 'tooth', name: 'Tooth', categories: ['home'], width: 64, source: 'mdi:tooth-outline' },
  { id: 'fan', name: 'Fan', categories: ['home'], width: 64, source: 'mdi:fan' },
  { id: 'washing-machine', name: 'Washing machine', categories: ['home'], width: 52, source: 'mdi:washing-machine' },
  { id: 'vacuum-cleaner', name: 'Vacuum cleaner', categories: ['home'], width: 64, source: 'mdi:vacuum-cleaner-outline' },
  { id: 'hair-dryer', name: 'Hair dryer', categories: ['home'], width: 64, source: 'mdi:hair-dryer-outline' },
  { id: 'iron', name: 'Iron', categories: ['home'], width: 64, source: 'tabler:ironing' },
  { id: 'scale', name: 'Balance scale', categories: ['work'], width: 64, source: 'tabler:scale' },
  { id: 'bed', name: 'Bed', categories: ['home'], width: 64, source: 'tabler:bed' },
  { id: 'dresser', name: 'Dresser', categories: ['home'], width: 64, source: 'mdi:dresser-outline' },
  { id: 'curtains', name: 'Curtains', categories: ['home'], width: 64, source: 'mdi:curtains' },
  { id: 'armchair', name: 'Armchair', categories: ['home'], width: 64, source: 'tabler:armchair' },
  { id: 'sofa', name: 'Sofa', categories: ['home'], width: 64, source: 'tabler:sofa' },
  { id: 'stool', name: 'Stool', categories: ['home'], width: 52, source: 'mdi:stool-outline' },
  { id: 'chair', name: 'Chair', categories: ['home'], width: 64, source: 'mdi:chair-outline' },
  { id: 'table', name: 'Table', categories: ['home'], width: 64, source: 'mdi:table-furniture' },
  { id: 'fireplace', name: 'Fireplace', categories: ['home'], width: 64, source: 'mdi:fireplace' },
  { id: 'rocking-chair', name: 'Rocking chair', categories: ['home'], width: 64, source: 'tabler:rocking-chair' },
  { id: 'picture-frame', name: 'Frame', categories: ['home'], width: 58, source: 'tabler:frame' },
  { id: 'helicopter', name: 'Helicopter', categories: ['engineering'], width: 64, source: 'tabler:helicopter' },
  { id: 'rocket', name: 'Rocket', categories: ['engineering'], width: 59, source: 'tabler:rocket' },
  { id: 'ufo', name: 'UFO', categories: ['engineering'], width: 64, source: 'tabler:ufo' },
  { id: 'tram', name: 'Tram', categories: ['engineering'], width: 46, source: 'mdi:tram' },
  { id: 'bus', name: 'Bus', categories: ['engineering'], width: 64, source: 'tabler:bus' },
  { id: 'taxi', name: 'Taxi', categories: ['engineering'], width: 58, source: 'mdi:taxi' },
  { id: 'motorcycle', name: 'Motorcycle', categories: ['engineering'], width: 64, source: 'tabler:motorbike' },
  { id: 'bicycle', name: 'Bicycle', categories: ['engineering'], width: 64, source: 'mdi:bicycle' },
  { id: 'excavator', name: 'Excavator', categories: ['engineering'], width: 64, source: 'tabler:backhoe' },
  { id: 'tractor', name: 'Tractor', categories: ['engineering'], width: 64, source: 'tabler:tractor' },
  { id: 'crane-truck', name: 'Crane truck', categories: ['engineering'], width: 64, source: 'tabler:car-crane' },
  { id: 'ambulance', name: 'Ambulance', categories: ['engineering'], width: 64, source: 'tabler:ambulance' },
  { id: 'police-car', name: 'Police car', categories: ['engineering'], width: 52, source: 'mdi:car-police' },
  { id: 'fire-engine', name: 'Fire engine', categories: ['engineering'], width: 64, source: 'tabler:firetruck' },
  { id: 'tank', name: 'Tank', categories: ['engineering'], width: 64, source: 'tabler:tank' },
  { id: 'ship', name: 'Ship', categories: ['engineering'], width: 64, source: 'tabler:ship' },
  { id: 'sailboat', name: 'Sailboat', categories: ['engineering'], width: 64, source: 'tabler:sailboat' },
  { id: 'submarine', name: 'Submarine', categories: ['engineering'], width: 64, source: 'tabler:submarine' },
  { id: 'tower', name: 'Eiffel Tower', categories: ['signs'], width: 64, source: 'tabler:building-eiffel-tower' },
  { id: 'palm-tree', name: 'Palm tree', categories: ['nature'], width: 56, source: 'mdi:palm-tree' },
  { id: 't-shirt', name: 'T-shirt', categories: ['home'], width: 64, source: 'tabler:shirt' },
  { id: 'bra', name: 'Bra', categories: ['home'], width: 64, source: 'mdi:bra' },
  { id: 'jersey', name: 'Jersey', categories: ['home'], width: 64, source: 'iconmind:team-jersey-outline-regular' },
  { id: 'shirt-tie', name: 'Tie', categories: ['home'], width: 42, source: 'tabler:tie' },
  { id: 'jacket', name: 'Jacket', categories: ['home'], width: 58, source: 'tabler:jacket' },
  { id: 'coat', name: 'Coat', categories: ['home'], width: 49, source: 'screenshot' },
  { id: 'hoodie', name: 'Hoodie', categories: ['home'], width: 50, source: 'screenshot' },
  { id: 'shirt', name: 'Shirt', categories: ['home'], width: 45, source: 'screenshot' },
  { id: 'sweater', name: 'Sweater', categories: ['home'], width: 64, source: 'screenshot' },
  { id: 'shorts', name: 'Shorts', categories: ['home'], width: 61, source: 'screenshot' },
  { id: 'skirt', name: 'Skirt', categories: ['home'], width: 64, source: 'screenshot' },
  { id: 'trousers', name: 'Trousers', categories: ['home'], width: 37, source: 'screenshot' },
  { id: 'long-sleeve-shirt', name: 'Long-sleeve shirt', categories: ['home'], width: 48, source: 'screenshot' },
  { id: 'tank-top', name: 'Tank top', categories: ['home'], width: 56, source: 'screenshot' },
  { id: 'briefs', name: 'Briefs', categories: ['home'], width: 64, source: 'screenshot' },
  { id: 'flip-flops', name: 'Flip-flops', categories: ['home'], width: 55, source: 'screenshot' },
  { id: 'dress-shoe', name: 'Dress shoe', categories: ['home'], width: 64, source: 'screenshot' },
  { id: 'scarf', name: 'Scarf', categories: ['home'], width: 53, source: 'screenshot' },
  { id: 'gloves', name: 'Gloves', categories: ['home'], width: 57, source: 'screenshot' },
  { id: 'poncho', name: 'Poncho', categories: ['home'], width: 63, source: 'screenshot' },
  { id: 'vest', name: 'Vest', categories: ['home'], width: 50, source: 'screenshot' },
  { id: 'dress', name: 'Dress', categories: ['home'], width: 61, source: 'screenshot' },
  { id: 'high-heels', name: 'High heels', categories: ['home'], width: 64, source: 'screenshot' },
  { id: 'boot', name: 'Boot', categories: ['home'], width: 35, source: 'screenshot' },
  { id: 'hat', name: 'Hat', categories: ['home'], width: 64, source: 'screenshot' },
  { id: 'cap', name: 'Cap', categories: ['home'], width: 64, source: 'screenshot' },
  { id: 'beanie', name: 'Beanie', categories: ['home'], width: 64, source: 'screenshot' },
  { id: 'socks', name: 'Socks', categories: ['home'], width: 51, source: 'screenshot' },
  { id: 'bow-tie', name: 'Bow', categories: ['home'], width: 64, source: 'fluent:bow-tie-24-regular' },
  { id: 'glasses', name: 'Glasses', categories: ['home'], width: 64, source: 'tabler:eyeglass-2' },
  { id: 'handbag', name: 'Handbag', categories: ['home'], width: 64, source: 'mdi:purse-outline' },
  { id: 'briefcase', name: 'Briefcase', categories: ['work'], width: 64, source: 'tabler:briefcase' },
  { id: 'suitcase', name: 'Suitcase', categories: ['home'], width: 64, source: 'screenshot' },
  { id: 'luggage', name: 'Luggage', categories: ['home'], width: 46, source: 'tabler:luggage' },
  { id: 'sunglasses', name: 'Sunglasses', categories: ['home'], width: 64, source: 'tabler:sunglasses' },
  { id: 'duffel-bag', name: 'Duffel bag', categories: ['home'], width: 64, source: 'screenshot' },
  { id: 'blanket', name: 'Blanket', categories: ['home'], width: 64, source: 'screenshot' },
  { id: 'wallet', name: 'Wallet', categories: ['home'], width: 60, source: 'screenshot' },
  { id: 'tv', name: 'TV', categories: ['engineering'], width: 64, source: 'tabler:device-tv' },
  { id: 'satellite-dish', name: 'Satellite', categories: ['engineering'], width: 64, source: 'tabler:satellite' },
  { id: 'boombox', name: 'Boombox', categories: ['engineering'], width: 64, source: 'mdi:boombox' },
  { id: 'cd', name: 'CD', categories: ['engineering'], width: 64, source: 'tabler:disc' },
  { id: 'vinyl', name: 'Vinyl record', categories: ['engineering'], width: 64, source: 'tabler:vinyl' },
  { id: 'sd-card', name: 'SD card', categories: ['engineering'], width: 52, source: 'tabler:device-sd-card' },
  { id: 'usb-stick', name: 'USB stick', categories: ['engineering'], width: 64, source: 'mdi:usb-flash-drive-outline' },
  { id: 'camera', name: 'Camera', categories: ['engineering'], width: 64, source: 'tabler:camera' },
  { id: 'camcorder', name: 'Camcorder', categories: ['engineering'], width: 64, source: 'tabler:video' },
  { id: 'microphone', name: 'Microphone', categories: ['engineering'], width: 52, source: 'tabler:microphone' },
  { id: 'speaker', name: 'Speaker', categories: ['engineering'], width: 64, source: 'tabler:volume' },
  { id: 'music-player', name: 'Music player', categories: ['engineering'], width: 46, source: 'mdi:ipod' },
  { id: 'headphones', name: 'Headphones', categories: ['engineering'], width: 58, source: 'tabler:headphones' },
  { id: 'tablet', name: 'Tablet', categories: ['engineering'], width: 52, source: 'tabler:device-tablet' },
  { id: 'clapperboard', name: 'Clapperboard', categories: ['engineering'], width: 64, source: 'mdi:clapperboard' },
  { id: 'movie-camera', name: 'Movie camera', categories: ['home'], width: 64, source: 'mdi:video-vintage' },
  { id: 'guitar', name: 'Guitar', categories: ['home'], width: 61, source: 'mdi:guitar-acoustic' },
  { id: 'piano', name: 'Piano', categories: ['home'], width: 64, source: 'tabler:piano' },
  { id: 'saxophone', name: 'Saxophone', categories: ['home'], width: 58, source: 'mdi:saxophone' },
  { id: 'trumpet', name: 'Trumpet', categories: ['home'], width: 64, source: 'mdi:trumpet' },
  { id: 'violin', name: 'Violin', categories: ['home'], width: 40, source: 'mdi:violin' },
  { id: 'treble-clef', name: 'Treble clef', categories: ['home'], width: 35, source: 'tabler:clef' },
  { id: 'music-note', name: 'Music note', categories: ['home'], width: 58, source: 'tabler:music' },
  { id: 'quadcopter', name: 'Quadcopter', categories: ['engineering'], width: 64, source: 'tabler:drone' },
  { id: 'hexacopter', name: 'Hexacopter', categories: ['engineering'], width: 64, source: 'qgc:HexaRotorX' },
  { id: 'octocopter', name: 'Octocopter', categories: ['engineering'], width: 64, source: 'qgc:OctoRotorX' },
  { id: 'flying-wing', name: 'Flying wing', categories: ['engineering'], width: 64, source: 'qgc:FlyingWing' },
  { id: 'plane-vtail', name: 'V-tail plane', categories: ['engineering'], width: 64, source: 'qgc:PlaneVTail' },
  { id: 'glider', name: 'Glider', categories: ['engineering'], width: 64, source: 'game-icons:glider' },
  { id: 'jet', name: 'Jet', categories: ['engineering'], width: 64, source: 'la:fighter-jet' },
  { id: 'parachute', name: 'Parachute', categories: ['engineering'], width: 64, source: 'tabler:parachute' },
  { id: 'robot-arm', name: 'Robot arm', categories: ['engineering'], width: 60, source: 'lucide:robot-arm' },
  { id: 'propeller', name: 'Propeller', categories: ['engineering'], width: 60, source: 'fontisto:propeller-3' },
  { id: 'motor', name: 'Electric motor', categories: ['engineering'], width: 61, source: 'qgc:MotorComponentIcon' },
  { id: 'esc', name: 'ESC', categories: ['engineering'], width: 64, source: 'qgc:EscIndicator' },
  { id: 'engine', name: 'Engine', categories: ['engineering'], width: 64, source: 'tabler:engine' },
  { id: 'turbine', name: 'Turbine / EDF', categories: ['engineering'], width: 64, source: 'mdi:turbine' },
  { id: 'gear', name: 'Gear', categories: ['engineering'], width: 64, source: 'tabler:settings' },
  { id: 'gears', name: 'Gears', categories: ['engineering'], width: 64, source: 'qgc:Gears' },
  { id: 'wheel', name: 'Wheel', categories: ['engineering'], width: 64, source: 'ph:tire' },
  { id: 'bearing', name: 'Bearing', categories: ['engineering'], width: 64, source: 'svgrepo:503235-bearing' },
  { id: 'suspension', name: 'Suspension spring', categories: ['engineering'], width: 28, source: 'tabler:car-suspension' },
  { id: 'rotate-cw', name: 'Clockwise', categories: ['engineering'], width: 58, source: 'tabler:rotate-clockwise' },
  { id: 'rotate-ccw', name: 'Counterclockwise', categories: ['engineering'], width: 58, source: 'tabler:rotate' },
  { id: 'microcontroller', name: 'Microcontroller', categories: ['engineering'], width: 64, source: 'streamline-ultimate:microchip-board' },
  { id: 'elevon', name: 'Elevon', categories: ['engineering'], width: 64, source: 'qgc:FlyingWing' },
  { id: 'rudder', name: 'Rudder', categories: ['engineering'], width: 64, source: 'mingcute:rudder-line' },
  { id: 'uart', name: 'UART', categories: ['engineering'], width: 58, source: 'mdi:swap-horizontal' },
  { id: 'navigation', name: 'Navigation', categories: ['engineering'], width: 64, source: 'lucide:navigation' },
  { id: 'battery-low', name: 'Battery low', categories: ['engineering'], width: 58, source: 'tabler:battery-1' },
  { id: 'battery-half', name: 'Battery half (storage)', categories: ['engineering'], width: 58, source: 'tabler:battery-2' },
  { id: 'battery-pack', name: 'Battery pack', categories: ['engineering'], width: 64, source: 'mdi:car-battery' },
  { id: 'charger', name: 'Charger', categories: ['engineering'], width: 64, source: 'carbon:charging-station' },
  { id: 'bolt', name: 'Lightning bolt', categories: ['engineering'], width: 52, source: 'tabler:bolt' },
  { id: 'power-button', name: 'Power button', categories: ['engineering'], width: 58, source: 'tabler:power' },
  { id: 'connector', name: 'Connector', categories: ['engineering'], width: 64, source: 'tabler:plug-connected' },
  { id: 'fuse', name: 'Fuse', categories: ['engineering'], width: 64, source: 'streamline-ultimate:electronics-fuse' },
  { id: 'switch', name: 'Switch', categories: ['engineering'], width: 64, source: 'tabler:circuit-switch-open' },
  { id: 'current-dc', name: 'Direct current', categories: ['engineering'], width: 64, source: 'mdi:current-dc' },
  { id: 'sine-wave', name: 'Sine wave (AC)', categories: ['engineering'], width: 64, source: 'tabler:wave-sine' },
  { id: 'square-wave', name: 'Square wave (PWM)', categories: ['engineering'], width: 64, source: 'tabler:wave-square' },
  { id: 'cable', name: 'Cable', categories: ['engineering'], width: 64, source: 'mdi:cable-data' },
  { id: 'chip', name: 'Chip / CPU', categories: ['engineering'], width: 64, source: 'tabler:cpu' },
  { id: 'circuit-board', name: 'Circuit board', categories: ['engineering'], width: 64, source: 'lucide:circuit-board' },
  { id: 'resistor', name: 'Resistor', categories: ['engineering'], width: 64, source: 'tabler:circuit-resistor' },
  { id: 'capacitor', name: 'Capacitor', categories: ['engineering'], width: 64, source: 'tabler:circuit-capacitor' },
  { id: 'diode', name: 'Diode', categories: ['engineering'], width: 64, source: 'tabler:circuit-diode' },
  { id: 'led', name: 'LED', categories: ['engineering'], width: 58, source: 'mdi:led-on' },
  { id: 'inductor', name: 'Inductor / coil', categories: ['engineering'], width: 64, source: 'tabler:circuit-inductor' },
  { id: 'magnet', name: 'Magnet', categories: ['engineering'], width: 58, source: 'tabler:magnet' },
  { id: 'bluetooth', name: 'Bluetooth', categories: ['engineering'], width: 40, source: 'tabler:bluetooth' },
  { id: 'serial-port', name: 'Serial port', categories: ['engineering'], width: 64, source: 'fluent:serial-port-24-regular' },
]

const byId = new Map(LABEL_ICONS.map((icon) => [icon.id, icon]))
const userById = new Map<string, LabelIcon>()

/** Each registered icon: its 64-dot dots and the heights shrunk from them so far. */
const dots = new Map<string, { source: IconBitmap; scaled: Map<number, IconBitmap> }>()

/**
 * Makes the user's icons available (replacing the previous set): they are
 * found by id and drawn like the curated ones.
 */
export function setUserIcons(icons: readonly UserIcon[]) {
  for (const id of userById.keys()) dots.delete(id)
  userById.clear()
  for (const icon of icons) {
    const { id, name, width } = icon
    userById.set(id, { id, name, categories: ['user'], width, source: 'user' })
    registerIconDots(id, unpackDots(icon))
  }
}

export function findLabelIcon(id: string): LabelIcon | undefined {
  return byId.get(id) ?? userById.get(id)
}

/** Width in dots of an icon drawn `height` dots tall. */
export function iconWidth(icon: LabelIcon, height: number): number {
  return scaledWidth(icon.width, height, ICON_GRID)
}

/** Hands over an icon's 64-dot dots (decoded from its PNG, or pasted). */
export function registerIconDots(id: string, source: IconBitmap) {
  if (source.height !== ICON_GRID)
    throw new Error(`Icon ${id} is ${source.height} dots tall, not ${ICON_GRID}`)
  dots.set(id, { source, scaled: new Map() })
}

/**
 * The icon as dots at `height`; cached. Blank (but the right size) if its
 * dots have not been registered.
 */
export function iconBitmap(icon: LabelIcon, height: number): IconBitmap {
  const entry = dots.get(icon.id)
  if (!entry) {
    const width = iconWidth(icon, height)
    return { width, height, data: new Uint8Array(width * height) }
  }
  let bitmap = entry.scaled.get(height)
  if (!bitmap) {
    bitmap = scaleIcon(entry.source, height)
    entry.scaled.set(height, bitmap)
  }
  return bitmap
}

/**
 * The bitmap as an SVG path of unit squares (runs merged per row), for
 * showing the exact dots in the page at any whole-number zoom.
 */
export function bitmapPath(bitmap: IconBitmap): string {
  let d = ''
  forEachRun(bitmap, (x, y, length) => (d += `M${x} ${y}h${length}v1h${-length}z`))
  return d
}

/** The picker's Recent list keeps this many icons. */
export const RECENT_ICON_LIMIT = 100

/**
 * Records that icon `id` was used at `now`, keeping only the `limit` most
 * recent: a new map of icon id → last use.
 */
export function rememberIconUse(
  lastUsed: Readonly<Record<string, number>>,
  id: string,
  now: number,
  limit = RECENT_ICON_LIMIT,
): Record<string, number> {
  const entries = Object.entries({ ...lastUsed, [id]: now })
  entries.sort((a, b) => b[1] - a[1])
  return Object.fromEntries(entries.slice(0, limit))
}
